<?php

/**
 * This is the model base class for the table "tbl_notifications".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Notifications".
 *
 * Columns in table "tbl_notifications" available as properties of the model,
 * followed by relations of table "tbl_notifications" available as properties of the model.
 *
 * @property integer $id
 * @property integer $receiver_id
 * @property integer $job_post_id
 * @property integer $notification_type_id
 * @property integer $is_read
 * @property string $time_sent
 *
 * @property User $receiver
 * @property JobPost $jobPost
 * @property NotificationType $notificationType
 */
abstract class BaseNotifications extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_notifications';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Notifications|Notifications', $n);
	}

	public static function representingColumn() {
		return 'time_sent';
	}

	public function rules() {
		return array(
			array('receiver_id', 'required'),
			array('receiver_id, job_post_id, notification_type_id, is_read', 'numerical', 'integerOnly'=>true),
			array('time_sent', 'safe'),
			array('job_post_id, notification_type_id, is_read', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, receiver_id, job_post_id, notification_type_id, is_read, time_sent', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'receiver' => array(self::BELONGS_TO, 'User', 'receiver_id'),
			'jobPost' => array(self::BELONGS_TO, 'JobPost', 'job_post_id'),
			'notificationType' => array(self::BELONGS_TO, 'NotificationType', 'notification_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'receiver_id' => null,
			'job_post_id' => null,
			'notification_type_id' => null,
			'is_read' => Yii::t('app', 'Is Read'),
			'time_sent' => Yii::t('app', 'Time Sent'),
			'receiver' => null,
			'jobPost' => null,
			'notificationType' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('receiver_id', $this->receiver_id);
		$criteria->compare('job_post_id', $this->job_post_id);
		$criteria->compare('notification_type_id', $this->notification_type_id);
		$criteria->compare('is_read', $this->is_read);
		$criteria->compare('time_sent', $this->time_sent, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
        
        /*public function beforeSave() {
            if($this->isNewRecord)
                $this->time_sent = new CDbExpression('NOW()');
            return parent::beforeSave();
        }*/
}