<?php

/**
 * This is the model base class for the table "tbl_user_skill".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserSkill".
 *
 * Columns in table "tbl_user_skill" available as properties of the model,
 * followed by relations of table "tbl_user_skill" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $skills_id
 *
 * @property Skill $skills
 * @property User $user
 */
abstract class BaseUserSkill extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_user_skill';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserSkill|UserSkills', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('user_id, skills_id', 'required'),
			array('user_id, skills_id', 'numerical', 'integerOnly'=>true),
			array('id, user_id, skills_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'skills' => array(self::BELONGS_TO, 'Skill', 'skills_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'skills_id' => null,
			'skills' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('skills_id', $this->skills_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}