<?php

/**
 * This is the model base class for the table "tbl_skill".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Skill".
 *
 * Columns in table "tbl_skill" available as properties of the model,
 * followed by relations of table "tbl_skill" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $desc
 * @property integer $approved
 *
 * @property JobPost[] $jobPosts
 * @property UserSkill[] $userSkills
 */
abstract class BaseSkill extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_skill';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Skill|Skills', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('approved', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>45),
			array('desc', 'length', 'max'=>255),
			array('name, desc, approved', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, desc, approved', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'jobPosts' => array(self::HAS_MANY, 'JobPost', 'skill_id'),
			'userSkills' => array(self::HAS_MANY, 'UserSkill', 'skills_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'desc' => Yii::t('app', 'Desc'),
			'approved' => Yii::t('app', 'Approved'),
			'jobPosts' => null,
			'userSkills' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('desc', $this->desc, true);
		$criteria->compare('approved', $this->approved);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}