<?php

/**
 * This is the model base class for the table "tbl_profile".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Profile".
 *
 * Columns in table "tbl_profile" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $user_id
 * @property string $lastname
 * @property string $firstname
 * @property integer $is_job_seeker
 * @property integer $is_job_giver
 *
 */
abstract class BaseProfile extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_profile';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Profile|Profiles', $n);
	}

	public static function representingColumn() {
		return 'lastname';
	}

	public function rules() {
		return array(
			array('user_id', 'required'),
			array('user_id, is_job_seeker, is_job_giver', 'numerical', 'integerOnly'=>true),
			array('lastname, firstname', 'length', 'max'=>50),
			array('lastname, firstname, is_job_seeker, is_job_giver', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, lastname, firstname, is_job_seeker, is_job_giver', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => Yii::t('app', 'User'),
			'firstname' => Yii::t('app', 'Firstname'),
                        'lastname' => Yii::t('app', 'Lastname'),
			'is_job_seeker' => Yii::t('app', 'Are you a Job Seeker?'),
			'is_job_giver' => Yii::t('app', 'Is Job Giver'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('is_job_seeker', $this->is_job_seeker);
		$criteria->compare('is_job_giver', $this->is_job_giver);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}