<?php

/**
 * This is the model base class for the table "tbl_notification_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NotificationType".
 *
 * Columns in table "tbl_notification_type" available as properties of the model,
 * followed by relations of table "tbl_notification_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $type
 *
 * @property Notifications[] $notifications
 */
abstract class BaseNotificationType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_notification_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NotificationType|NotificationTypes', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('type', 'required'),
			array('type', 'length', 'max'=>45),
			array('id, type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'notifications' => array(self::HAS_MANY, 'Notifications', 'notification_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'type' => Yii::t('app', 'Type'),
			'notifications' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('type', $this->type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}