<?php

/**
 * This is the model base class for the table "tbl_response".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Response".
 *
 * Columns in table "tbl_response" available as properties of the model,
 * followed by relations of table "tbl_response" available as properties of the model.
 *
 * @property integer $id
 * @property integer $message_id
 * @property string $message
 * @property integer $sender_id
 * @property integer $receiver_id
 * @property string $time_sent
 *
 * @property User $sender
 * @property User $receiver
 * @property Message $message0
 * @property ResponseData[] $responseDatas
 */
abstract class BaseResponse extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_response';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Response|Responses', $n);
	}

	public static function representingColumn() {
		return 'message';
	}

	public function rules() {
		return array(
			array('message_id, message, sender_id, receiver_id, time_sent', 'required'),
			array('message_id, sender_id, receiver_id', 'numerical', 'integerOnly'=>true),
			array('id, message_id, message, sender_id, receiver_id, time_sent', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sender' => array(self::BELONGS_TO, 'User', 'sender_id'),
			'receiver' => array(self::BELONGS_TO, 'User', 'receiver_id'),
			'message0' => array(self::BELONGS_TO, 'Message', 'message_id'),
			'responseDatas' => array(self::HAS_MANY, 'ResponseData', 'response_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'message_id' => null,
			'message' => Yii::t('app', 'Message'),
			'sender_id' => null,
			'receiver_id' => null,
			'time_sent' => Yii::t('app', 'Time Sent'),
			'sender' => null,
			'receiver' => null,
			'message0' => null,
			'responseDatas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('message_id', $this->message_id);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('sender_id', $this->sender_id);
		$criteria->compare('receiver_id', $this->receiver_id);
		$criteria->compare('time_sent', $this->time_sent, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}