<?php

/**
 * This is the model base class for the table "tbl_message".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Message".
 *
 * Columns in table "tbl_message" available as properties of the model,
 * followed by relations of table "tbl_message" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $message
 * @property integer $sender_id
 * @property integer $receiver_id
 * @property string $time_sent
 * @property string $updated_message_time
 *
 * @property User $sender
 * @property User $receiver
 * @property MessageData[] $messageDatas
 * @property Response[] $responses
 */
abstract class BaseMessage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_message';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Message|Messages', $n);
	}

	public static function representingColumn() {
		return 'message';
	}

	public function rules() {
		return array(
			array('message, sender_id, receiver_id', 'required'),
			array('sender_id, receiver_id', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>45),
			array('time_sent, updated_message_time', 'safe'),
			array('title, time_sent, updated_message_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, message, sender_id, receiver_id, time_sent, updated_message_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sender' => array(self::BELONGS_TO, 'User', 'sender_id'),
			'receiver' => array(self::BELONGS_TO, 'User', 'receiver_id'),
			'messageDatas' => array(self::HAS_MANY, 'MessageData', 'message_id'),
			'responses' => array(self::HAS_MANY, 'Response', 'message_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'message' => Yii::t('app', 'Message'),
			'sender_id' => null,
			'receiver_id' => null,
			'time_sent' => Yii::t('app', 'Time Sent'),
			'updated_message_time' => Yii::t('app', 'Updated Message Time'),
			'sender' => null,
			'receiver' => null,
			'messageDatas' => null,
			'responses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('sender_id', $this->sender_id);
		$criteria->compare('receiver_id', $this->receiver_id);
		$criteria->compare('time_sent', $this->time_sent, true);
		$criteria->compare('updated_message_time', $this->updated_message_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}