<?php

/**
 * This is the model base class for the table "tbl_message_data".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MessageData".
 *
 * Columns in table "tbl_message_data" available as properties of the model,
 * followed by relations of table "tbl_message_data" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $message_id
 * @property integer $is_read
 * @property integer $is_deleted
 * @property integer $starred
 * @property integer $is_sent
 * @property integer $is_received
 * @property integer $notify
 *
 * @property User $user
 * @property Message $message
 */
abstract class BaseMessageData extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_message_data';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MessageData|MessageDatas', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('user_id, message_id', 'required'),
			array('user_id, message_id, is_read, is_deleted, starred, is_sent, is_received, notify', 'numerical', 'integerOnly'=>true),
			array('is_read, is_deleted, starred, is_sent, is_received, notify', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, message_id, is_read, is_deleted, starred, is_sent, is_received, notify', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'message' => array(self::BELONGS_TO, 'Message', 'message_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'message_id' => null,
			'is_read' => Yii::t('app', 'Is Read'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'starred' => Yii::t('app', 'Starred'),
			'is_sent' => Yii::t('app', 'Is Sent'),
			'is_received' => Yii::t('app', 'Is Received'),
			'notify' => Yii::t('app', 'Notify'),
			'user' => null,
			'message' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('message_id', $this->message_id);
		$criteria->compare('is_read', $this->is_read);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('starred', $this->starred);
		$criteria->compare('is_sent', $this->is_sent);
		$criteria->compare('is_received', $this->is_received);
		$criteria->compare('notify', $this->notify);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}